apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: adservice
    project: hipstershopistio
    version: v1
  name: adservice
  namespace: default
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: adservice
      name: adservice
      project: hipstershopistio
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      labels:
        app: adservice
        name: adservice
        project: hipstershopistio
        version: v1
    spec:
      containers:
      - env:
        - name: BINDDELAY
          value: 0s
        - name: CONSECUTIVEERROR
          value: "0"
        - name: EXTRA_LATENCY
          value: 0s
        - name: LOGLEVEL
          value: debug
        - name: SRVURL
          value: :9555
        - name: STARTDELAY
          value: 0s
        - name: ZIPKIN_SERVICE_ADDR
          value: zipkin:9411
        image: simoneinsmann/adservice2:master
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9555
        name: adservice
        ports:
        - containerPort: 9555
          name: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9555
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 200m
            memory: 180Mi
      serviceAccountName: adservice
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: adservice
    name: adservice
    project: hipstershopistio
    service: adservice
  name: adservice
  namespace: default
spec:
  ports:
  - name: http
    port: 9555
    targetPort: 9555
  selector:
    app: adservice
    project: hipstershopistio
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adservice
  namespace: default