apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: adservice
    project: hipstershopistio
    version: v1
  name: adservice
  namespace: default
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: adservice
      name: adservice
      project: hipstershopistio
      version: v1
  template:
    metadata:
      labels:
        app: adservice
        name: adservice
        project: hipstershopistio
        version: v1
    spec:
      containers:
      - env:
        - name: HEALTH_PORT
          value: "9557"
        - name: DELAY_GETADS
          value: "150"
        - name: PORT
          value: "9555"
        - name: ZIPKIN_SERVICE_ADDR
          value: zipkin:9411
        image: simoneismann/adservice:master
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:9557
        name: adservice
        ports:
        - containerPort: 9555
          name: grpc
        - containerPort: 9557
          name: health
        readinessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:9557
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
      serviceAccountName: adservice
      nodeSelector:
        service: adservice
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: adservice
    name: adservice
    project: hipstershopistio
    service: adservice
  name: adservice
  namespace: default
spec:
  ports:
  - name: grpc-adservice
    port: 9555
    targetPort: 9555
  - name: health-adservice
    port: 9557
    targetPort: 9557
  selector:
    app: adservice
    project: hipstershopistio
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adservice
  namespace: default