apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loadgenerator
    project: hipstershopistio
    version: v1
  name: loadgenerator
  namespace: default
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: loadgenerator
      name: loadgenerator
      project: hipstershopistio
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: loadgenerator
        name: loadgenerator
        project: hipstershopistio
        version: v1
    spec:
      containers:
        - name: loadgenerator
          image: simoneismann/loadgenerator:master
          imagePullPolicy: Always
          ports:
          - containerPort: 8089
            name: http
      serviceAccountName: loadgenerator
      nodeSelector:
        service: loadgenerator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loadgenerator
  namespace: default