apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-cart
    project: hipstershopistio
    version: v1
  name: redis-cart
  namespace: default
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redis-cart
      name: redis-cart
      project: hipstershopistio
      version: v1
  template:
    metadata:
      labels:
        app: redis-cart
        name: redis-cart
        project: hipstershopistio
        version: v1
    spec:
      containers:
      - env:
        - name: ZIPKIN_SERVICE_ADDR
          value: zipkin:9411
        image: docker.io/library/redis:alpine
        imagePullPolicy: Always
        livenessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 6379
        name: redis-cart
        ports:
        - containerPort: 6379
          name: redis
        readinessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 6379
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
        volumeMounts:
        - mountPath: /data
          name: redis-data
      serviceAccountName: redis-cart
      nodeSelector:
        service: cartservice
      volumes:
      - emptyDir: {}
        name: redis-data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-cart
    name: redis-cart
    project: hipstershopistio
    service: redis-cart
  name: redis-cart
  namespace: default
spec:
  ports:
  - name: redis-redis-cart
    port: 6379
    targetPort: 6379
  selector:
    app: redis-cart
    project: hipstershopistio
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-cart
  namespace: default