apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: checkoutservice
    project: hipstershopistio
    version: v1
  name: checkoutservice
  namespace: default
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: checkoutservice
      name: checkoutservice
      project: hipstershopistio
      version: v1
  template:
    metadata:
      labels:
        app: checkoutservice
        name: checkoutservice
        project: hipstershopistio
        version: v1
    spec:
      containers:
      - env:
        - name: CART_SERVICE_ADDR
          value: cartservice:7070
        - name: CURRENCY_SERVICE_ADDR
          value: currencyservice:7000
        - name: EMAIL_SERVICE_ADDR
          value: emailservice:8080
        - name: HEALTH_PORT
          value: "5052"
        - name: PAYMENT_SERVICE_ADDR
          value: paymentservice:50051
        - name: PORT
          value: "5050"
        - name: DELAY_PLACE_ORDER
          value: "25"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: productcatalogservice:3550
        - name: SHIPPING_SERVICE_ADDR
          value: shippingservice:50051
        - name: ZIPKIN_SERVICE_ADDR
          value: zipkin:9411
        image: simoneismann/checkoutservice:master
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:5052
        name: checkoutservice
        ports:
        - containerPort: 5050
          name: grpc
        - containerPort: 5052
          name: health
        readinessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:5052
      serviceAccountName: checkoutservice
      nodeSelector:
        service: checkoutservice
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: checkoutservice
    name: checkoutservice
    project: hipstershopistio
    service: checkoutservice
  name: checkoutservice
  namespace: default
spec:
  ports:
  - name: grpc-checkoutservice
    port: 5050
    targetPort: 5050
  - name: health-checkoutservice
    port: 5052
    targetPort: 5052
  selector:
    app: checkoutservice
    project: hipstershopistio
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkoutservice
  namespace: default