apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: currencyservice
    project: hipstershopistio
    version: v1
  name: currencyservice
  namespace: default
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: currencyservice
      name: currencyservice
      project: hipstershopistio
      version: v1
  template:
    metadata:
      labels:
        app: currencyservice
        name: currencyservice
        project: hipstershopistio
        version: v1
    spec:
      containers:
      - env:
        - name: PORT
          value: "7000"
        - name: DELAY_CONVERT
          value: "140"
        - name: DELAY_GET_CURRENCIES
          value: "140"
        - name: ZIPKIN_SERVICE_ADDR
          value: zipkin:9411
        image: simoneismann/currencyservice:master
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:7002
        name: currencyservice
        ports:
        - containerPort: 7000
          name: grpc
        - containerPort: 7002
          name: health
        readinessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:7002
      serviceAccountName: currencyservice
      nodeSelector:
        service: currencyservice
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: currencyservice
    name: currencyservice
    project: hipstershopistio
    service: currencyservice
  name: currencyservice
  namespace: default
spec:
  ports:
  - name: grpc-currencyservice
    port: 7000
    targetPort: 7000
  - name: health-currencyservice
    port: 7002
    targetPort: 7002
  selector:
    app: currencyservice
    project: hipstershopistio
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: currencyservice
  namespace: default