apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zipkin
    project: hipstershopistio
    version: v1
  name: zipkin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
      name: zipkin
      project: hipstershopistio
      version: v1
  template:
    metadata:
      labels:
        app: zipkin
        name: zipkin
        project: hipstershopistio
        version: v1
    spec:
      containers:
      - env:
        - name: STORAGE_TYPE
          value: mysql
        - name: MYSQL_HOST
          value: mysql
        image: openzipkin/zipkin:2.21.7
        name: zipkin
        ports:
        - containerPort: 9411
      serviceAccountName: zipkin
      nodeSelector:
        service: zipkin
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zipkin
    name: zipkin
    project: hipstershopistio
    service: zipkin
  name: zipkin
  namespace: default
spec:
  ports:
  - name: conn-zipkin
    port: 9411
    targetPort: 9411
  selector:
    app: zipkin
    project: hipstershopistio
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zipkin
  namespace: default